name: build

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "build/libs/*.jar"
          generate_release_notes: true
          fail_on_unmatched_files: true